'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("POSTTEST_3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0ad335b1b4962118ce42f79914d3522a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0ad335b1b4962118ce42f79914d3522a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0e3274a31efb12df0f5897ae389d16dd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0e3274a31efb12df0f5897ae389d16dd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _140daaa49f1265f31d33ee24637ab084() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("140daaa49f1265f31d33ee24637ab084", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _50763a751a34ff3c7ea3a019b0a2cdac_removebg_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("50763a751a34ff3c7ea3a019b0a2cdac-removebg-preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _50763a751a34ff3c7ea3a019b0a2cdac_removebg_preview1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("50763a751a34ff3c7ea3a019b0a2cdac-removebg-preview1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _86a6181024ddf29e95529e99673ea700() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("86a6181024ddf29e95529e99673ea700", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b390f6d74ca9a1051d7280cdee7278ef() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b390f6d74ca9a1051d7280cdee7278ef", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b390f6d74ca9a1051d7280cdee7278ef1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b390f6d74ca9a1051d7280cdee7278ef1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Biru_Simpel_Garis_Kartu_Pelajar_Siswa_Sekolah() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Biru Simpel Garis Kartu Pelajar Siswa Sekolah", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c4aa0a7885e73c587bf3ae10315a4f37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c4aa0a7885e73c587bf3ae10315a4f37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c4aa0a7885e73c587bf3ae10315a4f371() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c4aa0a7885e73c587bf3ae10315a4f371", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d8cc72b1dae97964dfa0ed703ae8dd1b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d8cc72b1dae97964dfa0ed703ae8dd1b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d8cc72b1dae97964dfa0ed703ae8dd1b_removebg_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d8cc72b1dae97964dfa0ed703ae8dd1b-removebg-preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d8cc72b1dae97964dfa0ed703ae8dd1b1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d8cc72b1dae97964dfa0ed703ae8dd1b1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f455c860cd38df5ed921db2ce584cf6e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f455c860cd38df5ed921db2ce584cf6e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f455c860cd38df5ed921db2ce584cf6e1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f455c860cd38df5ed921db2ce584cf6e1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f455c860cd38df5ed921db2ce584cf6e2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f455c860cd38df5ed921db2ce584cf6e2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ombak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ombak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stephen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stephen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
